### ISSUE TITLE
Can I use pip as third party lib on adxe without breaking the MIT license of adxe?

### ISSUE THREAD

**Issue by aismann** [JavierDega/PiP#1]
adxe:
https://github.com/adxeproject/adxe

I wand add pip as a once more 2d physics lib (Chipmunk2D and Box2D be there too).

**Comment by aismann** [comment]
no longer on the focus of adxe.

**Comment by JavierDega** [comment]
Hello aismann! Sorry I didnt reply to your message on time. The lib wasnt done so I didnt think it was a good time for people to start implementing it yet, it was quite buggy and more importantly had some compilation issues on windows. I've spent a good amount of the last 6 months just dealing with cross platform issues and only now found a solution. 
With regards to the license, I've made it MIT Licensed now so it should be okay for it to be implemented in any project.
Let me know if you end up using it and ill try to be available to help :)
